/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.storage.view;

import com.storage.control.AdminTrs;
import com.storage.control.MyException;
import com.storage.model.Admin;
import java.awt.Frame;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erick Díaz
 */
public class frmAdminA extends javax.swing.JFrame {

    private final AdminTrs atrs = new AdminTrs();
    private List<Admin> admins = atrs.read();

    private void loadTable() {
        Object[] columns = {"Job", "First Name", "Last Name", "Password", "E-mail"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        for (Admin a : admins) {
            Object[] rows = {a.getJob(), a.getFirstName(),
                a.getLastName(), a.getPassword(), a.getEmail()};
            model.addRow(rows);
        }
        this.rSTableMetro2.setModel(model);
    }

    /**
     * Creates new form frmAdminA
     */
    public frmAdminA() {
        initComponents();
        setLocationRelativeTo(this);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSButton2 = new rojeru_san.RSButton();
        rSButton5 = new rojeru_san.RSButton();
        rSButton6 = new rojeru_san.RSButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jJob = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jFirst = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLast = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPass = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jEmail = new javax.swing.JTextField();
        rSButtonRiple1 = new rojeru_san.RSButtonRiple();
        rSButtonRiple2 = new rojeru_san.RSButtonRiple();
        rSButtonRiple3 = new rojeru_san.RSButtonRiple();
        jScrollPane2 = new javax.swing.JScrollPane();
        rSTableMetro2 = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1045, 501));

        jPanel1.setBackground(new java.awt.Color(25, 51, 77));
        jPanel1.setPreferredSize(new java.awt.Dimension(1040, 30));
        jPanel1.setRequestFocusEnabled(false);

        rSButton2.setBackground(new java.awt.Color(25, 51, 77));
        rSButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/storage/view/icon/back.png"))); // NOI18N
        rSButton2.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButton2MouseExited(evt);
            }
        });
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });

        rSButton5.setBackground(new java.awt.Color(25, 51, 77));
        rSButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/storage/view/icon/minus.png"))); // NOI18N
        rSButton5.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButton5MouseExited(evt);
            }
        });
        rSButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton5ActionPerformed(evt);
            }
        });

        rSButton6.setBackground(new java.awt.Color(25, 51, 77));
        rSButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/storage/view/icon/exit.png"))); // NOI18N
        rSButton6.setColorHover(new java.awt.Color(255, 255, 255));
        rSButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButton6MouseExited(evt);
            }
        });
        rSButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rSButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Job: ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jJob.setBackground(new java.awt.Color(255, 255, 255));
        jJob.setForeground(new java.awt.Color(102, 102, 102));
        jJob.setToolTipText("");
        jJob.setBorder(null);
        jPanel2.add(jJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 146, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 146, 10));

        jLabel2.setText("Firts Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jFirst.setBackground(new java.awt.Color(255, 255, 255));
        jFirst.setForeground(new java.awt.Color(102, 102, 102));
        jFirst.setToolTipText("");
        jFirst.setBorder(null);
        jPanel2.add(jFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 146, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 146, 10));

        jLabel3.setText("Last Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLast.setBackground(new java.awt.Color(255, 255, 255));
        jLast.setForeground(new java.awt.Color(102, 102, 102));
        jLast.setToolTipText("");
        jLast.setBorder(null);
        jPanel2.add(jLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 146, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 146, 10));

        jLabel4.setText("Password:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jPass.setBackground(new java.awt.Color(255, 255, 255));
        jPass.setForeground(new java.awt.Color(102, 102, 102));
        jPass.setToolTipText("");
        jPass.setBorder(null);
        jPanel2.add(jPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 146, -1));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 146, 10));

        jLabel5.setText("E-mail:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 146, 10));

        jEmail.setBackground(new java.awt.Color(255, 255, 255));
        jEmail.setForeground(new java.awt.Color(102, 102, 102));
        jEmail.setToolTipText("");
        jEmail.setBorder(null);
        jPanel2.add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 146, -1));

        rSButtonRiple1.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonRiple1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        rSButtonRiple1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/storage/view/icon/admin1.png"))); // NOI18N
        rSButtonRiple1.setText("Add");
        rSButtonRiple1.setColorHover(new java.awt.Color(25, 51, 77));
        rSButtonRiple1.setColorText(new java.awt.Color(25, 51, 77));
        rSButtonRiple1.setIconTextGap(30);
        rSButtonRiple1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButtonRiple1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonRiple1MouseExited(evt);
            }
        });
        rSButtonRiple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonRiple1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        rSButtonRiple2.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonRiple2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        rSButtonRiple2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/storage/view/icon/up2.png"))); // NOI18N
        rSButtonRiple2.setText("Update");
        rSButtonRiple2.setColorHover(new java.awt.Color(25, 51, 77));
        rSButtonRiple2.setColorText(new java.awt.Color(25, 51, 77));
        rSButtonRiple2.setIconTextGap(30);
        rSButtonRiple2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButtonRiple2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonRiple2MouseExited(evt);
            }
        });
        rSButtonRiple2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple2ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonRiple2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        rSButtonRiple3.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonRiple3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        rSButtonRiple3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/storage/view/icon/delete2.png"))); // NOI18N
        rSButtonRiple3.setText("Delete");
        rSButtonRiple3.setColorHover(new java.awt.Color(25, 51, 77));
        rSButtonRiple3.setColorText(new java.awt.Color(25, 51, 77));
        rSButtonRiple3.setIconTextGap(30);
        rSButtonRiple3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButtonRiple3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonRiple3MouseExited(evt);
            }
        });
        rSButtonRiple3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple3ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonRiple3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        rSTableMetro2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rSTableMetro2.setColorBackgoundHead(new java.awt.Color(25, 51, 77));
        rSTableMetro2.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        rSTableMetro2.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(rSTableMetro2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 750, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton2MouseEntered
        // TODO add your handling code here:
        rSButton2.setIcon(new ImageIcon("img\\back2.png"));
    }//GEN-LAST:event_rSButton2MouseEntered

    private void rSButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton2MouseExited
        // TODO add your handling code here:
        rSButton2.setIcon(new ImageIcon("img\\back.png"));
    }//GEN-LAST:event_rSButton2MouseExited

    private void rSButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton5MouseEntered
        // TODO add your handling code here:
        rSButton5.setIcon(new ImageIcon("img\\min2.png"));
    }//GEN-LAST:event_rSButton5MouseEntered

    private void rSButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton5MouseExited
        // TODO add your handling code here:
        rSButton5.setIcon(new ImageIcon("img\\minus.png"));
    }//GEN-LAST:event_rSButton5MouseExited

    private void rSButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton6MouseEntered
        // TODO add your handling code here:
        rSButton6.setIcon(new ImageIcon("img\\close2.png"));
    }//GEN-LAST:event_rSButton6MouseEntered

    private void rSButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton6MouseExited
        // TODO add your handling code here:
        rSButton6.setIcon(new ImageIcon("img\\exit.png"));
    }//GEN-LAST:event_rSButton6MouseExited

    private void rSButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rSButton6ActionPerformed

    private void rSButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton5ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_rSButton5ActionPerformed

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new frmAdmin().setVisible(true);
    }//GEN-LAST:event_rSButton2ActionPerformed

    private void rSButtonRiple2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple2MouseExited
        // TODO add your handling code here:
        rSButtonRiple2.setIcon(new ImageIcon("img\\up2.png"));
    }//GEN-LAST:event_rSButtonRiple2MouseExited

    private void rSButtonRiple2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple2MouseEntered
        // TODO add your handling code here:
        rSButtonRiple2.setIcon(new ImageIcon("img\\up.png"));
    }//GEN-LAST:event_rSButtonRiple2MouseEntered

    private void rSButtonRiple1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple1MouseExited
        // TODO add your handling code here:
        rSButtonRiple1.setIcon(new ImageIcon("img\\admin1.png"));
    }//GEN-LAST:event_rSButtonRiple1MouseExited

    private void rSButtonRiple1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple1MouseEntered
        // TODO add your handling code here:
        rSButtonRiple1.setIcon(new ImageIcon("img\\admin2.png"));
    }//GEN-LAST:event_rSButtonRiple1MouseEntered

    private void rSButtonRiple3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple3MouseExited
        // TODO add your handling code here:
        rSButtonRiple3.setIcon(new ImageIcon("img\\delete2.png"));
    }//GEN-LAST:event_rSButtonRiple3MouseExited

    private void rSButtonRiple3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonRiple3MouseEntered
        // TODO add your handling code here:
        rSButtonRiple3.setIcon(new ImageIcon("img\\delete.png"));
    }//GEN-LAST:event_rSButtonRiple3MouseEntered

    private void rSButtonRiple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple1ActionPerformed
        // TODO add your handling code here:
        if (!(jJob.getText().isEmpty() | jFirst.getText().isEmpty() | jLast.getText().isEmpty()
                | jPass.getText().isEmpty() | jEmail.getText().isEmpty())) {
            try {
                atrs.create(new Admin(jJob.getText(), jFirst.getText(),
                        jLast.getText(), jPass.getText(), jEmail.getText()));
                jEmail.setText(null);
                jJob.setText(null);
                jLast.setText(null);
                jFirst.setText(null);
                jPass.setText(null);
            } catch (MyException ex) {
                new ErrorMessage(new Frame(), true, true, ex.getMessage()).setVisible(true);
            } finally {
                loadTable();
            }
        } else {
            new ErrorMessage(new Frame(), true, true, "Please, complete all fields.").setVisible(true);
        }
    }//GEN-LAST:event_rSButtonRiple1ActionPerformed

    private void rSButtonRiple2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple2ActionPerformed
        // TODO add your handling code here:
        if (!(jJob.getText().isEmpty() | jEmail.getText().isEmpty())) {
            try {
                atrs.update(new Admin(jJob.getText(), atrs.searchAdminByEmail(jEmail.getText()).getFirstName(),
                        atrs.searchAdminByEmail(jEmail.getText()).getLastName(), atrs.searchAdminByEmail(jEmail.getText()).getPassword(),
                        jEmail.getText()));
                jEmail.setText(null);
                jJob.setText(null);
            } catch (MyException ex) {
                new ErrorMessage(new Frame(), true, true, ex.getMessage()).setVisible(true);
            } finally {
                loadTable();
            }
        } else if (!(jEmail.getText().isEmpty() | jPass.getText().isEmpty())) {
            try {
                atrs.update(new Admin(atrs.searchAdminByEmail(jEmail.getText()).getJob(), atrs.searchAdminByEmail(jEmail.getText()).getFirstName(),
                        atrs.searchAdminByEmail(jEmail.getText()).getLastName(), jPass.getText(),
                        atrs.searchAdminByEmail(jEmail.getText()).getEmail()));
                jEmail.setText(null);
                jJob.setText(null);
            } catch (MyException ex) {
                new ErrorMessage(new Frame(), true, true, ex.getMessage()).setVisible(true);
            } finally {
                loadTable();
            }
        } else {
            new ErrorMessage(new Frame(), true, true, "Please, complete all fields.").setVisible(true);
        }
    }//GEN-LAST:event_rSButtonRiple2ActionPerformed

    private void rSButtonRiple3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple3ActionPerformed
        // TODO add your handling code here:
        if (!jEmail.getText().isEmpty()) {
            try {
                atrs.delete(new Admin(null, null, null, null, jEmail.getText()));
                jEmail.setText(null);
            } catch (MyException ex) {
                new ErrorMessage(new Frame(), true, true, ex.getMessage()).setVisible(true);
            } finally {
                loadTable();
            }
        } else {
            new ErrorMessage(new Frame(), true, true, "Please, complete the E-mail.").setVisible(true);
        }
    }//GEN-LAST:event_rSButtonRiple3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdminA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdminA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdminA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdminA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdminA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jFirst;
    private javax.swing.JTextField jJob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jLast;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPass;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSButton rSButton5;
    private rojeru_san.RSButton rSButton6;
    private rojeru_san.RSButtonRiple rSButtonRiple1;
    private rojeru_san.RSButtonRiple rSButtonRiple2;
    private rojeru_san.RSButtonRiple rSButtonRiple3;
    private rojerusan.RSTableMetro rSTableMetro2;
    // End of variables declaration//GEN-END:variables
}
